//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DragonBones_UnityDragonBonesDataWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DragonBones.UnityDragonBonesData), typeof(UnityEngine.ScriptableObject));
		L.RegFunction("RemoveFromFactory", RemoveFromFactory);
		L.RegFunction("New", _CreateDragonBones_UnityDragonBonesData);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("dataName", get_dataName, set_dataName);
		L.RegVar("dragonBonesJSON", get_dragonBonesJSON, set_dragonBonesJSON);
		L.RegVar("textureAtlas", get_textureAtlas, set_textureAtlas);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateDragonBones_UnityDragonBonesData(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				DragonBones.UnityDragonBonesData obj = new DragonBones.UnityDragonBonesData();
				ToLua.Push(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: DragonBones.UnityDragonBonesData.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveFromFactory(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				DragonBones.UnityDragonBonesData obj = (DragonBones.UnityDragonBonesData)ToLua.CheckObject<DragonBones.UnityDragonBonesData>(L, 1);
				obj.RemoveFromFactory();
				return 0;
			}
			else if (count == 2)
			{
				DragonBones.UnityDragonBonesData obj = (DragonBones.UnityDragonBonesData)ToLua.CheckObject<DragonBones.UnityDragonBonesData>(L, 1);
				bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
				obj.RemoveFromFactory(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: DragonBones.UnityDragonBonesData.RemoveFromFactory");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_dataName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.UnityDragonBonesData obj = (DragonBones.UnityDragonBonesData)o;
			string ret = obj.dataName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index dataName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_dragonBonesJSON(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.UnityDragonBonesData obj = (DragonBones.UnityDragonBonesData)o;
			UnityEngine.TextAsset ret = obj.dragonBonesJSON;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index dragonBonesJSON on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_textureAtlas(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.UnityDragonBonesData obj = (DragonBones.UnityDragonBonesData)o;
			DragonBones.UnityDragonBonesData.TextureAtlas[] ret = obj.textureAtlas;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index textureAtlas on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_dataName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.UnityDragonBonesData obj = (DragonBones.UnityDragonBonesData)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.dataName = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index dataName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_dragonBonesJSON(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.UnityDragonBonesData obj = (DragonBones.UnityDragonBonesData)o;
			UnityEngine.TextAsset arg0 = (UnityEngine.TextAsset)ToLua.CheckObject<UnityEngine.TextAsset>(L, 2);
			obj.dragonBonesJSON = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index dragonBonesJSON on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_textureAtlas(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.UnityDragonBonesData obj = (DragonBones.UnityDragonBonesData)o;
			DragonBones.UnityDragonBonesData.TextureAtlas[] arg0 = ToLua.CheckObjectArray<DragonBones.UnityDragonBonesData.TextureAtlas>(L, 2);
			obj.textureAtlas = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index textureAtlas on a nil value");
		}
	}
}

