//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaFramework_TimerManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaFramework.TimerManager), typeof(Manager));
		L.RegFunction("AddTimerEvent", AddTimerEvent);
		L.RegFunction("RemoveTimerEvent", RemoveTimerEvent);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddTimerEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.TimerManager obj = (LuaFramework.TimerManager)ToLua.CheckObject<LuaFramework.TimerManager>(L, 1);
			LuaFramework.TimerInfo arg0 = (LuaFramework.TimerInfo)ToLua.CheckObject<LuaFramework.TimerInfo>(L, 2);
			obj.AddTimerEvent(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveTimerEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.TimerManager obj = (LuaFramework.TimerManager)ToLua.CheckObject<LuaFramework.TimerManager>(L, 1);
			LuaFramework.TimerInfo arg0 = (LuaFramework.TimerInfo)ToLua.CheckObject<LuaFramework.TimerInfo>(L, 2);
			obj.RemoveTimerEvent(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

