//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_HorizontalWrapModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.HorizontalWrapMode));
		L.RegVar("Wrap", get_Wrap, null);
		L.RegVar("Overflow", get_Overflow, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.HorizontalWrapMode>.Check = CheckType;
		StackTraits<UnityEngine.HorizontalWrapMode>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.HorizontalWrapMode arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.HorizontalWrapMode), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Wrap(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.HorizontalWrapMode.Wrap);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Overflow(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.HorizontalWrapMode.Overflow);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.HorizontalWrapMode o = (UnityEngine.HorizontalWrapMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

