//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ParticleSystemRenderSpaceWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.ParticleSystemRenderSpace));
		L.RegVar("View", get_View, null);
		L.RegVar("World", get_World, null);
		L.RegVar("Local", get_Local, null);
		L.RegVar("Facing", get_Facing, null);
		L.RegVar("Velocity", get_Velocity, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.ParticleSystemRenderSpace>.Check = CheckType;
		StackTraits<UnityEngine.ParticleSystemRenderSpace>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.ParticleSystemRenderSpace arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.ParticleSystemRenderSpace), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_View(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ParticleSystemRenderSpace.View);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_World(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ParticleSystemRenderSpace.World);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Local(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ParticleSystemRenderSpace.Local);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Facing(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ParticleSystemRenderSpace.Facing);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Velocity(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ParticleSystemRenderSpace.Velocity);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.ParticleSystemRenderSpace o = (UnityEngine.ParticleSystemRenderSpace)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

